project_id = "vwdxqtopxklebnszxrpu"

[functions.extract-criterios]
verify_jwt = false

[functions.analyze-personas]
verify_jwt = false

[functions.generate-proposal-model]
verify_jwt = false

[functions.simulate-proposal]
verify_jwt = false